services:
  postgres:
    image: postgres:15
    container_name: securepayment_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kst017
      POSTGRES_DB: payment_gateway_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: securepayment_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_gateway_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: kst017
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: securepayment_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
