version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kst017
      POSTGRES_DB: payment_gateway_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_gateway_db
      SPRING_DATASOURCE_USERNAME: surya
      SPRING_DATASOURCE_PASSWORD: password123

volumes:
  pgdata:
