backend:
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - "8080:8080"
  depends_on:
    - postgres
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_gateway_db
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: kst017
